version: '3'

services:
   postgres:
      image: postgres:13
      volumes:
         - ./postgres:/var/lib/postgresql/data
      environment:
         - POSTGRES_DB=my_store
         - POSTGRES_USER=cbx
         - POSTGRES_PASSWORD=123456
      ports:
         - 5432:5432

   pgadmin:
      image: dpage/pgadmin4:6
      environment:
         - PGADMIN_DEFAULT_EMAIL=admin@mail.com
         - PGADMIN_DEFAULT_PASSWORD=root
      ports:
         - 5050:80


# volumes:
#    postgres_db:
#       external: true
